### ISSUE TITLE
forum registration broken

### ISSUE THREAD

**Issue by qubolino** [makerplane/Documentation#3]
b/c of captcha i am unable to register to the forum.
<img width="1168" alt="Screenshot 2021-06-09 at 15 02 42" src="https://user-images.githubusercontent.com/35581024/121359427-c3c64c80-c933-11eb-9bfd-15d927918786.png">

**Comment by birkelbach** [comment]
It works for me.  My guess is that you have some kind of DNS problem.

**Comment by makerplane-jnicol** [comment]
I also just changed the spambot countermeasures to see if that makes a difference.  Note that you still need to send an email to contact at makerplane.org with your user name and email so that I can do the final registration.  We get hundreds of spambots mainly from Russia trying to automatically register every day.
